#!/bin/bash
TESTNAME=atlas_lustre
[[ $1 ]] &&  TESTNAME=$1
dorm=0
if [[ ${PBS_JOBID} ]]; then
SCRATCHFN=/data/atlas/brisbane/${PBS_JOBID}
else
  SCRATCHFN=/data/atlas/brisbane/$(hostname)
  dorm=1
fi

echo "scratch_contents" > $SCRATCHFN
echo "TEST: $TESTNAME - result: "
FAIL=0
[ `cat $SCRATCHFN` == "scratch_contents" ] || FAIL=1
rm ${SCRATCHFN}
if [ $FAIL -eq 1 ]; then
    echo FAIL
else
    echo OK
fi
exit $FAIL
