#!/bin/bash

function realpath {
echo $(cd `dirname $1`; pwd)/$(basename $1)
}
if [[ $1 ]]; then

if [ $1 = -h ] || [ $1 = --help ]; then
   echo usage $0 dir-to-schedule
   exit 0
fi
dir=$1
if ! [ -e $dir ] ; then

echo $dir does not exist
exit 1 
fi

dir=`realpath $dir`
shortdir=`echo $dir | sed 's/^\/data\/atlas//'`
todir=/data/atlas/scheduled-for-deletion/$shortdir
if [ -e $dir ]; then
  mkdir -p `dirname $todir `
fi
mv $dir $todir

fi

